### ISSUE TITLE
love this project, some questions

### ISSUE THREAD

**Issue by davidany** [xperiments/p1touch#13]
can you use fingers instead of stylus on resistive  screen? 
if not, would it be possible to order capacitive screen to use fingers instead of stylus? or would that affect code?

Also, you mentioned creating for larger size screens, I am pretty decent at design and coding, and if you need any
help getting that to work, I would gladly help in anyway i can.

**Comment by itsonlymedan** [comment]
Fingers work :) no stylus needed

**Comment by xperiments** [comment]
Larger screen sizes will come after 1.0 release....
