### ISSUE TITLE
Data is not saved

### ISSUE THREAD

**Issue by PrintModz** [xperiments/p1touch#14]
The problem here is that the data is not saved. After each restart, the printer data has to be re-entered and this is extremely annoying in the long run. Since the problem also exists with some others, it is not a mistake on my part.

Is there already a solution in sight?

**Comment by itsonlymedan** [comment]
Known issue check losing config issue

**Comment by grete12** [comment]
with me the config is also lost after the restart

**Comment by JudasBrutas** [comment]
Same bug here. Settings won't save after shut down. Thank you for all the hard work!

**Comment by xperiments** [comment]
Duplicate of #4

**Comment by PrintModz** [comment]
and new Update?
