### ISSUE TITLE
Source code missing

### ISSUE THREAD

**Issue by nurtext** [xperiments/p1touch#15]
Seems you're only providing the binary distribution, that's a no-go, because no one could check if the binary contains any malware or not. I would never ever use a controller unit on my printer which is connected to the internet and could theoretically do anything to my printer and I do not recommend this to anyone in general- at least until there will be source code available and we can check if it produces the same binary.

**Comment by nurtext** [comment]
I see, so basically this is a dupe of #2 - sorry should've done a quick search before opening a new issue.

**Comment by xperiments** [comment]
Duplicate of #2
