### ISSUE TITLE
Feature Request- Add Option to change screen timeout

### ISSUE THREAD

**Issue by screech24** [xperiments/p1touch#17]
Currently it seems the screen timeout is very short around 1 minute, which isn't very useful. Please add an option somewhere either on the screen itself or during wifi config that we can adjust to our liking. I understand the screen should NOT stay on full time to prevent pixel burn in but at least up to 15 minute timeout seems reasonable.

**Comment by nostalghia13** [comment]
I'd love for there to be a 15 minute display on time. I agree that it currently feels way too short.

**Comment by xperiments** [comment]
Next version will come w a configurable timer. Closing for now
