### ISSUE TITLE
Aux fan/ Part cooling fan doesn't show speed. 

### ISSUE THREAD

**Issue by screech24** [xperiments/p1touch#18]
There seems to be an issue at least for me where if I set the part cooling or aux fan to a speed of none 0 the P1Touch doesn't change the speed showed on screen even tho the fan is running. Speed always stays at 0. Maybe this is a known issue just wanted to point it out. Thanks Again for an Awesome Bambu MOD!!

**Comment by grete12** [comment]
I have the same problem
