### ISSUE TITLE
Larger screen support

### ISSUE THREAD

**Issue by MrmysteryV** [xperiments/p1touch#22]
I found some larger screens and would appreciate if you could try and port this to them!
7 inch - [7 inch](https://www.aliexpress.com/item/1005004952726089.html?spm=a2g0n.productlist.0.0.5fba2476EymRQH&browser_id=3e20fdb8d8f64f7a99b95db2e9e51918&aff_trace_key=f1d1c9dd62a54f53a01b6ee043c5383a-1693224471558-00950-UneMJZVf&aff_platform=msite&m_page_id=ghxzhxsepsmcawul18a3c0e75f42442f900a9a2fc1&gclid=&pdp_npi=4%40dis%21GBP%2122.68%2122.68%21%21%21201.96%21%21%402100b77316932246952872307d0781%2112000031135431789%21sea%21UK%210%21A&algo_pvid=d76b7d1d-51ae-4fd6-a0e8-2a3daa4fed4f&search_p4p_id=202308280511352823730592938710000460569_5) 
3.5 inch - [3.5 inch](https://www.aliexpress.com/item/1005004632953455.html?spm=a2g0n.productlist.0.0.425750b6XFDDt7&browser_id=3e20fdb8d8f64f7a99b95db2e9e51918&aff_trace_key=f1d1c9dd62a54f53a01b6ee043c5383a-1693224471558-00950-UneMJZVf&aff_platform=msite&m_page_id=ghxzhxsepsmcawul18a3c0c2eed240751302e73275&gclid=&pdp_npi=4%40dis%21GBP%2112.03%2112.03%21%21%21107.10%21%21%402100b88516932245460311154d0745%2112000029911293172%21sea%21UK%210%21A&algo_pvid=7dd77533-fc4c-401f-bd52-15f893534b19&search_p4p_id=202308280509061907773071527400000444493_3&_universallink=1&m_page_id=ghxzhxsepsmcawul18a3c0c2eed240751302e73275&_universallink=1&m_page_id=ghxzhxsepsmcawul18a3c0c2eed240751302e73275) 
5 inch - [5 inch ](https://www.aliexpress.com/item/1005004952694042.html?browser_id=3e20fdb8d8f64f7a99b95db2e9e51918&aff_trace_key=f1d1c9dd62a54f53a01b6ee043c5383a-1693224471558-00950-UneMJZVf&aff_platform=msite&m_page_id=ghxzhxsepsmcawul18a3c202cb4175fb54b31c6e7f&gclid=&pdp_npi=4%40dis%21GBP%2122.68%2118.59%21%21%21201.96%21%21%402100b20d16932258561836812d0733%2112000031135228930%21sea%21UK%210%21A&algo_pvid=d127fbd2-f45b-4a85-99c4-6ddbe1c771b9&search_p4p_id=202308280530562716940868767020000496969_8) 
Thanks

**Comment by danakaiggy** [comment]
please with the 3.5 vinch     thats what they sent me when i ordered the one that you suggested.
