### ISSUE TITLE
Default wifi password - 12345678 to be something else

### ISSUE THREAD

**Issue by php4umagento** [xperiments/p1touch#24]
Hello
 If I have neighbour who has P1Touch I can connect to his and he can connect to mine as password is same for all of us, can this be more personalised - based on MAC address or something else?

Don't want anyone to connect to my P1Touch

**Comment by php4umagento** [comment]
Thanks for your great work so far, when is next release planned?

**Comment by xperiments** [comment]
No ETA at the moment. I will be working on this from next week to fix the
known issues and begin cleaning the code and testing it privately until
release then source the code... But mostly 2-3 weeks

**Comment by fdebeer** [comment]
> Hello If I have neighbour who has P1Touch I can connect to his and he can connect to mine as password is same for all of us, can this be more personalised - based on MAC address or something else?
> 
> Don't want anyone to connect to my P1Touch

when setup and configured and connected to your printer the wifi p1touch network is no longer available.

**Comment by xperiments** [comment]
No more need of Wifi Access Point Setup in next version... Closing for now
