### ISSUE TITLE
Connects but no control of printer

### ISSUE THREAD

**Issue by McClean0815** [xperiments/p1touch#27]
Hi,
i tried this nice project with my x1c and it connects nice. It shows me correct values (AMS colors are not right) but no control is possible, Setting temperature, turn light on/off. There is no error message but nothing happens

Greetings,Steffen

**Comment by fdebeer** [comment]
maybe because its written for the p1p or p1s?

**Comment by McClean0815** [comment]
I do not think that the mqtt implementation differs in the x1 model firmwares. This would make no sense...

**Comment by xperiments** [comment]
A new version is in the works...
Btw Can you disconnect the AMS and test it?
I think is related to the size of the buffer, and with ams exceeds the
limits ATM
