### ISSUE TITLE
Issue with connecting to the router WIFI

### ISSUE THREAD

**Issue by php4umagento** [xperiments/p1touch#3]
After setting up wifi via web I can see in the logs

[ 94946][E][WiFiGeneric.cpp:1578] hostByName(): DNS Failed for [P1PTouch][MQTT] ---- CONNECTION FAIL ----: -2

`[ 52323][E][WebServer.cpp:649] _handleRequest(): request handler not found
*wm:Connecting to NEW AP: MGAROUTER
*wm:connectTimeout not set, ESP waitForConnectResult... 
*wm:Connect to new AP [SUCCESS] 
*wm:Got IP Address: 
*wm:192.168.1.140 
[ 93838][E][WebServer.cpp:649] _handleRequest(): request handler not found
*wm:config portal exiting 
[P1PTouch][WifiManager] WiFi CONNECTED
[P1PTouch][FS] Config Saved
[P1PTouch][WifiManager] Local IP: 192.168.1.140
[P1PTouch][MQTT] Connecting
[ 94946][E][WiFiGeneric.cpp:1578] hostByName(): DNS Failed for 
[P1PTouch][MQTT] ---- CONNECTION FAIL ----: -2
*wm:resetSettings 
*wm:SETTINGS ERASED 
[P1PTouch][FS] Delete config
ets Jul 29 2019 12:21:46`

**Comment by xperiments** [comment]
This seems a problem with your connection. Have you solved it?
Closed for the moment, reopen if needed. Thx
