### ISSUE TITLE
Storage of the data

### ISSUE THREAD

**Issue by PrintModz** [xperiments/p1touch#30]
When will there finally be an update so that the login data is saved? Otherwise, this is all pointless.

**Comment by itsonlymedan** [comment]
Join the fb group and sign up for the beta it's very close.

**Comment by PrintModz** [comment]
Link?

**Comment by fdebeer** [comment]
https://m.facebook.com/groups/284441287626603/?ref=share&mibextid=S66gvF

**Comment by TackleBerryCrash** [comment]
> When will there finally be an update so that the login data is saved? Otherwise, this is all pointless.

yes it will be very soon. 

There are nicer way to say things, you are just rude and your issue is "pointless"
