### ISSUE TITLE
P1PTouch Web Installer URL ?

### ISSUE THREAD

**Issue by grete12** [xperiments/p1touch#33]
P1PTouch Web Installer ?

**Comment by TackleBerryCrash** [comment]
You have to be part of the closed beta group, which is not taking entries at this time anymore.
Please wait for the publisc release

**Comment by grete12** [comment]
I just need the web installer url. what does this have to do with closed beta?

**Comment by grete12** [comment]
Please be so kind and include me in the closed beta. I am very interested in this project. I bought the necessary hardware a few weeks ago.

**Comment by TackleBerryCrash** [comment]
It does, because you have to be part of beta testers to be able to get that url
