### ISSUE TITLE
Screen timeout not working

### ISSUE THREAD

**Issue by szaman-89** [xperiments/p1touch#34]
Using default 15m screen timeout dont work as is should (maybe another options either). Screen still turned on with last touch used at least 30 min before.

**Comment by TackleBerryCrash** [comment]
I just tested it. My timeout works, but try this change it to 10 then to 15 back and wait.
I think I know what is happening

**Comment by szaman-89** [comment]
Did you checked it while printing? In my case after printing finished screen turned out and without any changes functionality work as is should. Need to wait for next printing session to test more.

**Comment by xperiments** [comment]
While printing screen is on all the time
