### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by SzilagyiR** [xperiments/p1touch#35]
How can I reset the modul old configuration?

The web installer gives error: Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL.
Holding the button but nothing happens, the old software runing on the screen.

Thanks!

**Comment by TackleBerryCrash** [comment]
Installer erases the device prior to install. Do you see that on the screen ?

**Comment by xperiments** [comment]
Seems a driver problem. Have you installed the correct drivers? if so, Can you try rebooting your computer completely and try again?

**Comment by parrothd** [comment]
Same here, it was setup via the old web setup program, now it doesn't see the device when connected.

**Comment by xperiments** [comment]
Can you try using this software for the first flash? 

Download the 0.8.2 firmware http://retroconsol.es/products/p1touch/ota/p1touch.0.8.2.bin

Flash it with this utility:

https://github.com/esphome/esphome-flasher/releases

**Comment by SzilagyiR** [comment]
Neither the web installer nor the esp flasher not seen the com port.

The driver must be ok, the first intallation wenth smooth two weeks berfore.

**Comment by TackleBerryCrash** [comment]
Mac or PC

**Comment by SzilagyiR** [comment]
Pc

**Comment by parrothd** [comment]
I had 2 bad cables, windows would only power on the p1 touch, not see it.

**Comment by TackleBerryCrash** [comment]
open up the device manager and see what ports you have before plugging in also after pluggin in 
also dont use front IO, try back IO

**Comment by TackleBerryCrash** [comment]
> I had 2 bad cables, windows would only power on the p1 touch, not see it.

oh yes, it has to be a data cable. :)

**Comment by TackleBerryCrash** [comment]
what solved it ? :)

**Comment by SzilagyiR** [comment]
Switching the usb cable :)

**Comment by TackleBerryCrash** [comment]
I have two rules in this life 
never trust a fart and never trust a cable :)

**Comment by SzilagyiR** [comment]
Thanks fo everyone, who tried to help!
