### ISSUE TITLE
TFT firmware uploader issue

### ISSUE THREAD

**Issue by chrisping12** [xperiments/p1touch#44]
Each attempt at trying to update my display with the firmware I receive a message that the"

Looking at the closed issues on this rep I may have just missed the boat? I bought a bunch of TFT's to hopefully get this up and running on my P1P and P1S's. 

Hopefully I am missing something or using incorrect procedure?Or did I miss the boat on the beta testing for P1 Touch?

Thanks,

**Comment by chrisping12** [comment]
Apologies..
"Failed to initialize. Try resetting your device or holding the BOOT button while clicking INSTALL."

**Comment by TackleBerryCrash** [comment]
make sure your device is connected with a proper data cable. 
try with another cable first
