### ISSUE TITLE
Setting Options Missing.

### ISSUE THREAD

**Issue by chrisping12** [xperiments/p1touch#45]
I cannot find on any screen inside the P1touch where I can select OTA updates. I also cannot find any firmware.bin files anywhere on the site. 

The only item I see in setting is Aux fan and chamber fan.

Can you help?

**Comment by TackleBerryCrash** [comment]
please use discord for help. This place is for issues

**Comment by chrisping12** [comment]
Can you send me the link to P1Touch discord?

**Comment by chrisping12** [comment]
I never received an beta invite email. Any other way to access the discord now?

**Comment by xperiments** [comment]
If you have not signup for the beta no

**Comment by chrisping12** [comment]
Is there any current location I can download the most current version of the firmware? 
Or as Requested is there any possibility of joining the beta testing though I am a couple days past?
