### ISSUE TITLE
hi，sir，I have a better shell on top of P1P

### ISSUE THREAD

**Issue by muzixiaoyang** [xperiments/p1touch#50]

**Comment by muzixiaoyang** [comment]
https://pan.baidu.com/s/1nw5KS7TUHMWPm2mDpGZ23A?pwd=mxqv 
key：mxqv

**Comment by xperiments** [comment]
Hi thanks.
I will write down this data and put it on the Readme w user contributed models.
Can you upload it to makerworld so it is avaliable for all?
I am unable to download the file as needs registration an all is in China writing

I will close the issue as is not an issue

**Comment by muzixiaoyang** [comment]
> 嗨，谢谢。我将写下这些数据并将其放在用户贡献的自述文件中。你能把它上传到创客世界，这样它就可以供所有人使用吗？我无法下载文件，因为需要注册，一切都在中国写作
> 
> 我将关闭问题，因为不是问题

Hi!o(*￣▽￣*)ブSir~
This is a new website👉https://www.thingiverse.com/thing:6238053
