### ISSUE TITLE
Filament on holder may be tangled error everytime

### ISSUE THREAD

**Issue by jmc71479** [xperiments/p1touch#52]
I keep getting 12FF800000020001: The filament on the spool holder may be tangled by or stuck,” with every new print, but it runs. It happens when printer says cloud slice queue, I think, right before it downloads to printer.  Error stays on screen until acknowledged.  Happened with v0.8.6, and I updated to v0.8.14 tonight and is still happening.  This is on P1P with P1S upgrades, Firmware v. 01.04.00.08, Printing from Bambu Studio v. 1.7.6.92. I tried to attach video of it happening, but this doesn’t seem to allow video.  Image of error attached.
![IMG_7996](https://github.com/xperiments/p1touch/assets/142958413/2c228846-ae95-48fc-b7dd-92e90400e92d)

**Comment by TackleBerryCrash** [comment]
Can you check the HMS on the printer ? Do you see the error there also  ?

**Comment by jmc71479** [comment]
I don’t see any errors on the printer itself when this happens, or on Bambu studio.




Jeremy M. Carroll

On Sep 25, 2023, at 9:59 PM, Orkun Kaya ***@***.***> wrote:

﻿

Can you check the HMS on the printer ? Do you see the error there also ?

**Comment by xperiments** [comment]
Yeah, I was reporting a level that bambustudio does not report. 
Will fix

**Comment by xperiments** [comment]
Fixed in 0.8.17. Can you check. I close meanwhile. Reopen if needed
