### ISSUE TITLE
MQTT error on new beta and add reset option to screen

### ISSUE THREAD

**Issue by parrothd** [xperiments/p1touch#58]
Had a power outage today and when p1 and printer came back online got MQTT error and had to remove all configuration on the sdcard and resetup device. 

Maybe add a way to reset from the P1 boot screen, the website erase option doesn't clear the SDcard. :)

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   656][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40110c60 arg=0x3ffbe788
XTouch][SD] SD Card Type: [XTouch][SD] SDSC
[XTouch][SD] SD Card Size: 120MB
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /wifi.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 10.0.0.10
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][MQTT] Connecting
[ 24475][E][ssl_client.cpp:129] start_ssl_client(): socket error on fd 48, errno: 113, "Software caused connection abort"
[ 24476][E][WiFiClientSecure.cpp:144] connect(): start_ssl_client: -1
[XTouch][MQTT] ---- CONNECTION FAIL ----: -2
ets Jul 29 2019 12:21:46

**Comment by TackleBerryCrash** [comment]
This can be solved by reinstalling between OTAs if happens. Thanks for reporting
