### ISSUE TITLE
Pair Printers have no way to connect this

### ISSUE THREAD

**Issue by 3PrintD-Solution** [xperiments/p1touch#59]
Unfortunately I can't pair my 2 P1Ps. The green button has no function.

LOG

rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13192
load:0x40080400,len:3028
entry 0x400805e4
[XTouch][SCREEN] Setup
[   650][E][esp32-hal-cpu.c:110] addApbChangeCallback(): duplicate func=0x40111b5c arg=0x3ffbfc3c
XTouch][SD] SD Card Type: [XTouch][SD] SDHC
[XTouch][SD] SD Card Size: 29821MB
[XTouch][SD] Reading JSON file: /wifi.json
[XTouch][SD] Reading JSON file: /xtouch/settings.json
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-pair.json
[XTouch][FS] Checking for touch config
[XTouch][TOUCH] Load from disk
[XTouch][SD] Reading JSON file: /wifi.json
[XTOUCH][CONNECTION] Connecting to WiFi ..
[XTOUCH][CONNECTION] Connected to the WiFi network with IP: 10.1.1.227
[XTouch][SD] Reading JSON file: /xtouch/printer-pair.json
[XTouch][SD] Error Reading JSON File: /xtouch/printer-pair.json
[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][SD] Writting JSON file: /xtouch/printer-ips.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json
[XTouch][SD] Reading JSON file: /xtouch/printer-ips.json
[XTouch][SD] Writting JSON file: /xtouch/printer-ips.json
[XTouch][SD] Reading JSON file: /xtouch/printer.json

Think the problem is here
[XTouch][SD] Error Reading JSON File: /xtouch/printer-pair.json

What can I do to fix the error?

![PXL_20230930_084054948](https://github.com/xperiments/p1touch/assets/88507685/7e54bbf9-19eb-4de4-aade-fd531080465a)
![PXL_20230930_084045508](https://github.com/xperiments/p1touch/assets/88507685/96278f44-2f2d-4985-a1da-2034d71f301c)

**Comment by xperiments** [comment]
Please contact us in Discord. We can try to help yo there

**Comment by 3PrintD-Solution** [comment]
Thanks. The Discord Name?

**Comment by xperiments** [comment]
If you have access to the beta. You have the invitation in an email. I
can't give you directions here. Or DM me directly in twitter @xps3riments

**Comment by xperiments** [comment]
Closed as was a touch miss configuration
