### ISSUE TITLE
touch is unresponsive im using exact same board as you linked followed alll steps touch works fine when it asks me to click the x in corners but them after that ther is no touch at all

### ISSUE THREAD

**Issue by philhiggy** [xperiments/p1touch#6]
im using exact same board as you linked followed alll steps touch works fine when it asks me to click the x in corners but them after that there is no touch at all

**Comment by ZachWSays** [comment]
Try to reset configs, reflash it and when entering the info make sure your serial number is all caps. I had issues before doing that.

**Comment by philhiggy** [comment]
works now thankyou was capitals it needed
