### ISSUE TITLE
how can i change colour ?

### ISSUE THREAD

**Issue by CalvinLeong8208** [xperiments/p1touch#8]
my screen white and purple colour ... didnt look normal .... try to reinstall again .. still a same ... why like that ?

**Comment by CalvinLeong8208** [comment]
![IMG_9714](https://github.com/xperiments/p1touch/assets/142827729/85dfeff0-cdd6-433b-9201-509521f04d0d)
![IMG_9710](https://github.com/xperiments/p1touch/assets/142827729/a7593afc-474c-4438-a25d-0105ef133e38)
mine esp32 come with type-c and mirco usb ... mirco usb didnt work with pc .. but type-c can connect to pc ... mean mirco cant flash the rom ... side panels and ATM ? didnt get you ... newbie here ....

**Comment by xperiments** [comment]
Umm seems a new model. I will buy one when back. Mine has only microusb but
I bought it last year.. btw is yours 2.8 or 3.5 inch?

**Comment by itsonlymedan** [comment]
This is strange I have only bought mine recently and mine is not like that at all.

**Comment by xperiments** [comment]
Can you share a link or image?

**Comment by CalvinLeong8208** [comment]
mine is 2.8 inch .....

**Comment by itsonlymedan** [comment]
Out of a small sample piece 32 people we have identified that only 2 people out of the 32 have USB C everyone else has micro
